<?php

namespace Drupal\Tests\bos311\Kernel;

use \Drupal\KernelTests\KernelTestBase;
use Drupal\bos311\Record;

class CreateEntityTest extends KernelTestBase {

  /**
   * {@inheritdoc}
   */
  protected static $modules = ['bos311', 'node', 'user', 'system'];

  protected $record;

  public function setUp()
  {
    $this->record = new Record(
      'abc123',
      'open',
      'Other',
      'The quick brown fox',
      '2020-04-04',
      '162 commercial street',
      '-72.001',
      '42'
    );
    parent::setUp(); // TODO: Change the autogenerated stub
  }

  public function testCreate() {
    $this->record->create();

    $this->assertEqual(2, 2);
  }

}
